spring.datasource.url=jdbc:postgresql://localhost:5432/prodemics
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=prodemics
spring.sql.init.mode=never