spring.datasource.url=jdbc:postgresql://localhost:5432/prodemics
spring.datasource.username=postgres
spring.datasource.password=${DATA_SOURCE_PASSWORD:not-configured}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=prodemics
spring.sql.init.mode=never

jwt.secret=${JWT_SECRET:not-configured}
jwt.expiration=3600000
jwt.issuer=prodemics